---
- name: Setup NFC Jukebox
  hosts: all
  become: yes
  tasks:
    - name: Run raspi-config to enable I2C
      command: sudo raspi-config nonint do_i2c 0

    - name: Install needed packages
      ansible.builtin.apt:
        pkg:
        - libnfc6
        - libnfc-bin 
        - libnfc-examples

    - name: Ensure NFC device configuration is set in /etc/nfc/libnfc.conf
      ansible.builtin.blockinfile:
        path: /etc/nfc/libnfc.conf
        block: |
          device.name = "PN532 over I2C"
          device.connstring = "pn532_i2c:/dev/i2c-1"